# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # M: Master Node
    # W: Worker Node
    M = 1
    W = 1
    
    (1..W).each do |w|
        config.vm.define "ansible-client00#{w}" do |cfg|
            cfg.vm.box = "bento/ubuntu-22.04"
            cfg.vm.provider "virtualbox" do |vb|
                vb.name = "ansible-client00#{w}"
                vb.memory = "1024"
                vb.cpus = 1
            end
            cfg.vm.host_name = "ansible-client00#{w}"
            cfg.vm.network "private_network", ip: "192.168.1.#{w}"
            cfg.vm.network "forwarded_port", guest: 22, host: "6000#{w}", auto_correct: true, id: "ssh"
            cfg.vm.network "forwarded_port", guest: 80, host: "6008#{w}", auto_correct: true
        end
    end

    #ansible-server
    (1..M).each do |m|
        config.vm.define "ansible-server#{m}" do |cfg|
            cfg.vm.box = "bento/ubuntu-22.04"
            cfg.vm.provider "virtualbox" do |vb|
                vb.name="ansible-server#{m}"
                vb.memory = "1024"
                vb.cpus = 2
            end
            cfg.vm.host_name = "ansible-server#{m}"
            cfg.vm.network "private_network", ip: "192.168.1.#{m}0"
            cfg.vm.network "forwarded_port", guest: 22, host: "600#{m}0", auto_correct: true, id: "ssh"
            # cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true
            cfg.vm.provision "shell", inline: "apt update"
            cfg.vm.provision "shell", inline: "apt install software-properties-common"
            cfg.vm.provision "shell", inline: "add-apt-repository --yes --update ppa:ansible/ansible"
            cfg.vm.provision "shell", inline: "apt install ansible -y"
        end
    end
end